[package]
name = "class08"
version = "0.1.0"
authors = ["odin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Relative path and absolute path difference

[dependencies]
my_lib = {path = "my_lib"}